'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('./lib/api');

module.exports = {
  version: require('./package.json').version,
  platformVersion: require('zapier-platform-core').version,

  authentication: {
    type: 'custom',
    fields: [
      {
        "key": "api_key",
        "label": "API Key",
        "type": "password",
        "required": true,
        "helpText": "Create a key at [invowerk.dev](https://invowerk.dev/go/zapier?to=/app/api-keys)."
      },
    ],
    test: api.testAuth,
  },

  beforeRequest: [api.addApiKey],

  creates: {
    get_me: require('./creates/get_me'),
    parse_invoice: require('./creates/parse_invoice'),
    convert_invoice: require('./creates/convert_invoice'),
    generate_invoice: require('./creates/generate_invoice'),
    explain_codes: require('./creates/explain_codes'),
    render_invoice: require('./creates/render_invoice'),
    validate_invoice: require('./creates/validate_invoice'),
  },
};
