'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "POST",
  "path": "/v1/convert",
  "body": "form",
  "output": "text",
  "fields": [
    {
      "name": "target_syntax",
      "location": "query",
      "type": "string"
    },
    {
      "name": "target_flavor",
      "location": "query",
      "type": "string"
    },
    {
      "name": "format",
      "location": "query",
      "type": "string"
    },
    {
      "name": "file",
      "location": "file",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "convert_invoice",
  "noun": "invowerk",
  "display": {
    "label": "Convert an e-invoice between UBL and CII",
    "description": "Convert an e-invoice between UBL and CII."
  },
  "operation": {
    "inputFields": [
      {
        "key": "target_syntax",
        "label": "Target syntax",
        "required": true,
        "type": "string",
        "helpText": "The XML syntax to convert to: 'cii' or 'ubl'.",
        "choices": [
          "cii",
          "ubl"
        ]
      },
      {
        "key": "target_flavor",
        "label": "Target flavor",
        "required": false,
        "type": "string",
        "helpText": "Optional rule set of the result: 'en16931' or 'xrechnung'. Without it the flavor of the source is kept.",
        "choices": [
          "en16931",
          "xrechnung"
        ]
      },
      {
        "key": "format",
        "label": "Format",
        "required": false,
        "type": "string",
        "helpText": "'json' returns {xml, syntax, flavor, self_validation}; omitted returns raw application/xml."
      },
      {
        "key": "file",
        "label": "File",
        "required": true,
        "type": "file",
        "helpText": "The invoice file (XML or PDF)."
      }
    ],
    "sample": {
      "text": "sample",
      "content_type": "application/xml"
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
