'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "GET",
  "path": "/v1/explain",
  "body": null,
  "output": "json",
  "fields": [
    {
      "name": "code",
      "location": "query",
      "type": "array"
    },
    {
      "name": "lang",
      "location": "query",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "explain_codes",
  "noun": "invowerk",
  "display": {
    "label": "Explain an error code",
    "description": "Explain rule codes and invowerk's own `IW-*` Hinweise in German or English."
  },
  "operation": {
    "inputFields": [
      {
        "key": "code",
        "label": "Code",
        "required": true,
        "type": "string",
        "list": true,
        "helpText": "One or more codes; repeat the parameter: ?code=BR-DE-21&code=IW-IBAN."
      },
      {
        "key": "lang",
        "label": "Lang",
        "required": false,
        "type": "string",
        "helpText": "Language of the explanation, `de` or `en`. Without it, the Accept-Language header decides, otherwise German."
      }
    ],
    "sample": {
      "lang": "sample",
      "explanations": []
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
