'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "POST",
  "path": "/v1/generate",
  "body": "json",
  "output": "text",
  "fields": [
    {
      "name": "format",
      "location": "query",
      "type": "string"
    },
    {
      "name": "syntax",
      "location": "json",
      "type": "string"
    },
    {
      "name": "flavor",
      "location": "json",
      "type": "string"
    },
    {
      "name": "invoice_number",
      "location": "json",
      "type": "string"
    },
    {
      "name": "issue_date",
      "location": "json",
      "type": "string"
    },
    {
      "name": "currency",
      "location": "json",
      "type": "string"
    },
    {
      "name": "invoice_type_code",
      "location": "json",
      "type": "string"
    },
    {
      "name": "buyer_reference",
      "location": "json",
      "type": "string"
    },
    {
      "name": "due_date",
      "location": "json",
      "type": "string"
    },
    {
      "name": "payment_iban",
      "location": "json",
      "type": "string"
    },
    {
      "name": "seller",
      "location": "json",
      "type": "object"
    },
    {
      "name": "buyer",
      "location": "json",
      "type": "object"
    },
    {
      "name": "lines",
      "location": "json",
      "type": "array"
    },
    {
      "name": "tax_breakdown",
      "location": "json",
      "type": "array"
    },
    {
      "name": "totals",
      "location": "json",
      "type": "object"
    }
  ]
};

const DEFINITION = {
  "key": "generate_invoice",
  "noun": "invowerk",
  "display": {
    "label": "Create an e-invoice from JSON",
    "description": "Create an EN 16931 e-invoice from JSON."
  },
  "operation": {
    "inputFields": [
      {
        "key": "format",
        "label": "Format",
        "required": false,
        "type": "string",
        "helpText": "'json' returns {xml, syntax, flavor, self_validation}; omitted returns raw application/xml."
      },
      {
        "key": "syntax",
        "label": "Syntax",
        "required": false,
        "type": "string",
        "helpText": "XML syntax of the invoice: 'ubl' or 'cii'.",
        "choices": [
          "cii",
          "ubl"
        ],
        "default": "ubl"
      },
      {
        "key": "flavor",
        "label": "Flavor",
        "required": false,
        "type": "string",
        "helpText": "Rule set: 'en16931' (plain EN 16931) or 'xrechnung' (German rules).",
        "choices": [
          "en16931",
          "xrechnung"
        ],
        "default": "en16931"
      },
      {
        "key": "invoice_number",
        "label": "Invoice number",
        "required": true,
        "type": "string",
        "helpText": "Invoice number (BT-1)."
      },
      {
        "key": "issue_date",
        "label": "Issue date",
        "required": true,
        "type": "string",
        "helpText": "Issue date, 'YYYY-MM-DD' (BT-2)."
      },
      {
        "key": "currency",
        "label": "Currency",
        "required": false,
        "type": "string",
        "helpText": "Currency code, ISO 4217, e.g. 'EUR' (BT-5).",
        "default": "EUR"
      },
      {
        "key": "invoice_type_code",
        "label": "Invoice type code",
        "required": false,
        "type": "string",
        "helpText": "Invoice type code from UNTDID 1001; '380' is a commercial invoice (BT-3).",
        "default": "380"
      },
      {
        "key": "buyer_reference",
        "label": "Buyer reference",
        "required": false,
        "type": "string",
        "helpText": "Buyer reference, in Germany often the Leitweg-ID (BT-10). Required for flavor 'xrechnung' (BR-DE-15), optional for plain EN 16931."
      },
      {
        "key": "due_date",
        "label": "Due date",
        "required": false,
        "type": "string",
        "helpText": "Payment due date, 'YYYY-MM-DD' (BT-9)."
      },
      {
        "key": "payment_iban",
        "label": "Payment iban",
        "required": false,
        "type": "string",
        "helpText": "IBAN of the payee account for a bank transfer (BT-84)."
      },
      {
        "key": "seller",
        "label": "Seller",
        "required": true,
        "type": "text",
        "helpText": "The seller (BG-4). (JSON)"
      },
      {
        "key": "buyer",
        "label": "Buyer",
        "required": true,
        "type": "text",
        "helpText": "The buyer (BG-7). (JSON)"
      },
      {
        "key": "lines",
        "label": "Lines",
        "required": true,
        "type": "text",
        "helpText": "One or more invoice lines (BG-25). (JSON)"
      },
      {
        "key": "tax_breakdown",
        "label": "Tax breakdown",
        "required": true,
        "type": "text",
        "helpText": "One or more VAT breakdowns, one per VAT category and rate (BG-23). (JSON)"
      },
      {
        "key": "totals",
        "label": "Totals",
        "required": true,
        "type": "text",
        "helpText": "The document totals (BG-22). (JSON)"
      }
    ],
    "sample": {
      "text": "sample",
      "content_type": "application/xml"
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
