'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "POST",
  "path": "/v1/parse",
  "body": "form",
  "output": "json",
  "fields": [
    {
      "name": "file",
      "location": "file",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "parse_invoice",
  "noun": "invowerk",
  "display": {
    "label": "Read an e-invoice into JSON",
    "description": "Read an existing e-invoice into JSON keyed on EN 16931 Business Terms."
  },
  "operation": {
    "inputFields": [
      {
        "key": "file",
        "label": "File",
        "required": true,
        "type": "file",
        "helpText": "The invoice file (XML or PDF)."
      }
    ],
    "sample": {
      "model": {},
      "detection": {},
      "source": "sample"
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
