'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "POST",
  "path": "/v1/render",
  "body": "form",
  "output": "text",
  "fields": [
    {
      "name": "lang",
      "location": "query",
      "type": "string"
    },
    {
      "name": "format",
      "location": "query",
      "type": "string"
    },
    {
      "name": "file",
      "location": "file",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "render_invoice",
  "noun": "invowerk",
  "display": {
    "label": "Render an e-invoice as HTML",
    "description": "Render an XML e-invoice as a readable HTML page."
  },
  "operation": {
    "inputFields": [
      {
        "key": "lang",
        "label": "Lang",
        "required": false,
        "type": "string",
        "helpText": "Label language, 'de' or 'en'. Default: Accept-Language, then 'de'."
      },
      {
        "key": "format",
        "label": "Format",
        "required": false,
        "type": "string",
        "helpText": "'json' returns {html, lang, flavor, syntax}; omitted returns raw text/html."
      },
      {
        "key": "file",
        "label": "File",
        "required": false,
        "type": "file",
        "helpText": "The invoice XML as a multipart file part."
      }
    ],
    "sample": {
      "text": "sample",
      "content_type": "text/html"
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
