'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
const api = require('../lib/api');

const REQUEST = {
  "method": "POST",
  "path": "/v1/validate",
  "body": "form",
  "output": "json",
  "fields": [
    {
      "name": "explain",
      "location": "query",
      "type": "boolean"
    },
    {
      "name": "lang",
      "location": "query",
      "type": "string"
    },
    {
      "name": "file",
      "location": "file",
      "type": "string"
    }
  ]
};

const DEFINITION = {
  "key": "validate_invoice",
  "noun": "invowerk",
  "display": {
    "label": "Check an e-invoice",
    "description": "Check an e-invoice against EN 16931 and the German rules."
  },
  "operation": {
    "inputFields": [
      {
        "key": "explain",
        "label": "Explain",
        "required": false,
        "type": "boolean",
        "default": "false"
      },
      {
        "key": "lang",
        "label": "Lang",
        "required": false,
        "type": "string",
        "default": "de"
      },
      {
        "key": "file",
        "label": "File",
        "required": true,
        "type": "file",
        "helpText": "The invoice file (XML or PDF)."
      }
    ],
    "sample": {
      "valid": true,
      "verdict_source": "sample",
      "local_verdict": "sample",
      "disagreement": true,
      "lane": "sample",
      "official_verdict": "sample",
      "scenario": {},
      "pdfa_verdict": "sample",
      "detection": {},
      "errors": {},
      "findings": [],
      "rulesets": {},
      "evidence": {},
      "e_rechnung_de": {},
      "hints": []
    }
  }
};

module.exports = {
  ...DEFINITION,
  operation: {
    ...DEFINITION.operation,
    perform: (z, bundle) => api.call(z, REQUEST, bundle.inputData),
  },
};
