/* globals describe, expect, test */
'use strict';

// Generated by listing-sync (infra scripts/listing_sync/connectors/zapier.py); edits are overwritten.
// Live calls need a key (API_KEY=... npm test) and spend its credits; a
// binary answer is stashed as a Zapier file, which also needs ZAPIER_DEPLOY_KEY.
const zapier = require('zapier-platform-core');

const App = require('../index');

const appTester = zapier.createAppTester(App);
zapier.tools.env.inject();

const live = process.env.API_KEY ? test : test.skip;
const liveFile = process.env.API_KEY && process.env.ZAPIER_DEPLOY_KEY ? test : test.skip;
const authData = { api_key: process.env.API_KEY };

describe('authentication', () => {
  live('accepts the key', async () => {
    const result = await appTester(App.authentication.test, { authData });
    expect(result).toBeTruthy();
  });
});

describe('creates', () => {
  live('get_me', async () => {
    const inputData = {};
    const result = await appTester(App.creates.get_me.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  live('parse_invoice', async () => {
    const inputData = {
      "file": "https://invowerk.dev/app-static/demo/beispiel-xrechnung.xml"
    };
    const result = await appTester(App.creates.parse_invoice.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  live('convert_invoice', async () => {
    const inputData = {
      "target_syntax": "cii",
      "file": "https://invowerk.dev/app-static/demo/beispiel-xrechnung.xml"
    };
    const result = await appTester(App.creates.convert_invoice.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  live('generate_invoice', async () => {
    const inputData = {
      "syntax": "ubl",
      "flavor": "xrechnung",
      "invoice_number": "INV-001",
      "issue_date": "2026-01-15",
      "currency": "EUR",
      "buyer_reference": "04011000-1234512345-06",
      "due_date": "2026-02-15",
      "payment_iban": "DE75512108001245126199",
      "seller": {
        "address": {
          "city": "Berlin",
          "country_code": "DE",
          "post_code": "10115"
        },
        "contact_email": "accounts@example.com",
        "contact_name": "Accounts",
        "contact_phone": "+49 30 1234567",
        "electronic_address": "seller@example.com",
        "name": "Seller GmbH",
        "vat_id": "DE123456789"
      },
      "buyer": {
        "address": {
          "city": "Munich",
          "country_code": "DE",
          "post_code": "80331"
        },
        "electronic_address": "buyer@example.com",
        "name": "Buyer AG"
      },
      "lines": [
        {
          "line_net_amount": "100.00",
          "name": "Widget",
          "net_price": "100.00",
          "quantity": "1",
          "tax_category": "S",
          "tax_rate": "19.00"
        }
      ],
      "tax_breakdown": [
        {
          "category": "S",
          "rate": "19.00",
          "tax_amount": "19.00",
          "taxable_amount": "100.00"
        }
      ],
      "totals": {
        "line_total": "100.00",
        "tax_exclusive": "100.00",
        "tax_inclusive": "119.00"
      }
    };
    const result = await appTester(App.creates.generate_invoice.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  test('explain_codes is defined (its input comes from an earlier step)', () => {
    expect(typeof App.creates.explain_codes.operation.perform).toBe('function');
  });

  live('render_invoice', async () => {
    const inputData = {
      "file": "https://invowerk.dev/app-static/demo/beispiel-xrechnung.xml"
    };
    const result = await appTester(App.creates.render_invoice.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });

  live('validate_invoice', async () => {
    const inputData = {
      "file": "https://invowerk.dev/app-static/demo/beispiel-xrechnung.xml"
    };
    const result = await appTester(App.creates.validate_invoice.operation.perform, {
      authData,
      inputData,
    });
    expect(Object.keys(result).length).toBeGreaterThan(0);
  });
});
