// Generated by listing-sync from https://api.invowerk.dev/openapi.json — do not edit.
import type {
	IDataObject,
	IExecuteFunctions,
	IHttpRequestMethods,
	IN8nHttpFullResponse,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
	JsonObject,
} from 'n8n-workflow';
import {
	jsonParse,
	NodeApiError,
	NodeConnectionTypes,
	NodeOperationError,
	sleep,
} from 'n8n-workflow';

const BASE_URL = 'https://api.invowerk.dev';
const CREDENTIAL = 'invowerkApi';
const POLL_SECONDS = 5;
const POLL_LIMIT = 360;

type Location = 'path' | 'query' | 'json' | 'form' | 'file';

interface ApiField {
	name: string;
	param: string;
	location: Location;
	type: string;
	required: boolean;
}

interface ApiOperation {
	method: IHttpRequestMethods;
	path: string;
	body: 'none' | 'json' | 'form';
	fields: ApiField[];
	job?: { poll: string; result: string };
}

function jsonValue(value: unknown): unknown {
	return typeof value === 'string' ? jsonParse(value) : value;
}

async function request(
	ctx: IExecuteFunctions,
	method: IHttpRequestMethods,
	path: string,
	qs: IDataObject = {},
	body?: FormData | IDataObject,
): Promise<IN8nHttpFullResponse> {
	return (await ctx.helpers.httpRequestWithAuthentication.call(ctx, CREDENTIAL, {
		method,
		url: BASE_URL + path,
		qs,
		arrayFormat: 'repeat',
		body,
		encoding: 'arraybuffer',
		returnFullResponse: true,
	})) as IN8nHttpFullResponse;
}

async function send(
	ctx: IExecuteFunctions,
	op: ApiOperation,
	i: number,
): Promise<IN8nHttpFullResponse> {
	const extra = ctx.getNodeParameter('additionalFields', i, {}) as IDataObject;
	const binary = ctx.getInputData()[i].binary ?? {};
	let path = op.path;
	const qs: IDataObject = {};
	const json: IDataObject = {};
	const form = new FormData();
	for (const field of op.fields) {
		const topLevel = field.required || field.location === 'file';
		const value = topLevel ? ctx.getNodeParameter(field.param, i, '') : extra[field.param];
		if (value === undefined || value === '') continue;
		if (field.location === 'file') {
			const property = String(value);
			if (!field.required && !binary[property]) continue;
			const meta = ctx.helpers.assertBinaryData(i, property);
			const buffer = await ctx.helpers.getBinaryDataBuffer(i, property);
			form.append(
				field.name,
				new Blob([new Uint8Array(buffer)], { type: meta.mimeType }),
				meta.fileName ?? field.name,
			);
		} else if (field.location === 'path') {
			path = path.replace(`{${field.name}}`, encodeURIComponent(String(value)));
		} else if (field.location === 'query') {
			qs[field.name] =
				field.type === 'array'
					? String(value)
							.split(',')
							.map((v) => v.trim())
							.filter((v) => v)
					: (value as IDataObject[keyof IDataObject]);
		} else if (field.location === 'json') {
			json[field.name] = (
				field.type === 'object' || field.type === 'array' ? jsonValue(value) : value
			) as IDataObject[keyof IDataObject];
		} else {
			form.append(field.name, String(value));
		}
	}
	const body = op.body === 'form' ? form : op.body === 'json' ? json : undefined;
	return await request(ctx, op.method, path, qs, body);
}

function onePath(path: string, id: string): string {
	return path.replace(/\{[^}]+\}/, encodeURIComponent(id));
}

async function decode(
	ctx: IExecuteFunctions,
	response: IN8nHttpFullResponse,
	i: number,
): Promise<INodeExecutionData> {
	const header = response.headers['content-type'];
	const mimeType = String(Array.isArray(header) ? header[0] : (header ?? '')).split(';')[0].trim();
	const data = Buffer.from(response.body as ArrayBuffer);
	if (mimeType === 'application/json' || mimeType.endsWith('+json')) {
		const parsed = jsonParse<unknown>(data.toString('utf8'));
		const item =
			parsed && typeof parsed === 'object' && !Array.isArray(parsed)
				? (parsed as IDataObject)
				: ({ data: parsed } as IDataObject);
		return { json: item, pairedItem: { item: i } };
	}
	if (mimeType.startsWith('text/') || mimeType.endsWith('xml')) {
		return { json: { data: data.toString('utf8'), mimeType }, pairedItem: { item: i } };
	}
	const disposition = String(response.headers['content-disposition'] ?? '');
	const fileName = /filename="?([^";]+)"?/.exec(disposition)?.[1];
	const file = await ctx.helpers.prepareBinaryData(data, fileName, mimeType || undefined);
	return {
		json: { fileName: file.fileName, mimeType: file.mimeType, fileSize: file.fileSize },
		binary: { data: file },
		pairedItem: { item: i },
	};
}

async function runJob(
	ctx: IExecuteFunctions,
	job: { poll: string; result: string },
	submitted: IDataObject,
	i: number,
): Promise<IN8nHttpFullResponse> {
	const id = String(submitted.job_id ?? submitted.id ?? '');
	const poll = OPERATIONS[job.poll];
	const result = OPERATIONS[job.result];
	for (let attempt = 0; attempt < POLL_LIMIT; attempt++) {
		await sleep(POLL_SECONDS * 1000);
		const state = (await decode(ctx, await request(ctx, poll.method, onePath(poll.path, id)), i))
			.json;
		if (state.status === 'succeeded') {
			return await request(ctx, result.method, onePath(result.path, id));
		}
		if (state.status === 'failed') {
			throw new NodeOperationError(ctx.getNode(), `Job ${id} failed: ${String(state.error ?? '')}`, {
				itemIndex: i,
			});
		}
	}
	throw new NodeOperationError(ctx.getNode(), `Job ${id} did not finish in time`, { itemIndex: i });
}

const OPERATIONS: Record<string, ApiOperation> = {
	get_me: {
		method: 'GET',
		path: '/v1/me',
		body: 'none',
		fields: [],
	},
	parse_invoice: {
		method: 'POST',
		path: '/v1/parse',
		body: 'form',
		fields: [
			{
				name: 'file',
				param: 'binaryPropertyName',
				location: 'file',
				type: 'string',
				required: true,
			},
		],
	},
	convert_invoice: {
		method: 'POST',
		path: '/v1/convert',
		body: 'form',
		fields: [
			{
				name: 'target_syntax',
				param: 'targetSyntax',
				location: 'query',
				type: 'string',
				required: true,
			},
			{
				name: 'target_flavor',
				param: 'targetFlavor',
				location: 'query',
				type: 'string',
				required: false,
			},
			{
				name: 'format',
				param: 'format',
				location: 'query',
				type: 'string',
				required: false,
			},
			{
				name: 'file',
				param: 'binaryPropertyName',
				location: 'file',
				type: 'string',
				required: true,
			},
		],
	},
	generate_invoice: {
		method: 'POST',
		path: '/v1/generate',
		body: 'json',
		fields: [
			{
				name: 'format',
				param: 'format',
				location: 'query',
				type: 'string',
				required: false,
			},
			{
				name: 'syntax',
				param: 'syntax',
				location: 'json',
				type: 'string',
				required: false,
			},
			{
				name: 'flavor',
				param: 'flavor',
				location: 'json',
				type: 'string',
				required: false,
			},
			{
				name: 'invoice_number',
				param: 'invoiceNumber',
				location: 'json',
				type: 'string',
				required: true,
			},
			{
				name: 'issue_date',
				param: 'issueDate',
				location: 'json',
				type: 'string',
				required: true,
			},
			{
				name: 'currency',
				param: 'currency',
				location: 'json',
				type: 'string',
				required: false,
			},
			{
				name: 'invoice_type_code',
				param: 'invoiceTypeCode',
				location: 'json',
				type: 'string',
				required: false,
			},
			{
				name: 'buyer_reference',
				param: 'buyerReference',
				location: 'json',
				type: 'string',
				required: false,
			},
			{
				name: 'due_date',
				param: 'dueDate',
				location: 'json',
				type: 'string',
				required: false,
			},
			{
				name: 'payment_iban',
				param: 'paymentIban',
				location: 'json',
				type: 'string',
				required: false,
			},
			{
				name: 'seller',
				param: 'seller',
				location: 'json',
				type: 'object',
				required: true,
			},
			{
				name: 'buyer',
				param: 'buyer',
				location: 'json',
				type: 'object',
				required: true,
			},
			{
				name: 'lines',
				param: 'lines',
				location: 'json',
				type: 'array',
				required: true,
			},
			{
				name: 'tax_breakdown',
				param: 'taxBreakdown',
				location: 'json',
				type: 'array',
				required: true,
			},
			{
				name: 'totals',
				param: 'totals',
				location: 'json',
				type: 'object',
				required: true,
			},
		],
	},
	explain_codes: {
		method: 'GET',
		path: '/v1/explain',
		body: 'none',
		fields: [
			{
				name: 'code',
				param: 'code',
				location: 'query',
				type: 'array',
				required: true,
			},
			{
				name: 'lang',
				param: 'lang',
				location: 'query',
				type: 'string',
				required: false,
			},
		],
	},
	render_invoice: {
		method: 'POST',
		path: '/v1/render',
		body: 'form',
		fields: [
			{
				name: 'lang',
				param: 'lang',
				location: 'query',
				type: 'string',
				required: false,
			},
			{
				name: 'format',
				param: 'format',
				location: 'query',
				type: 'string',
				required: false,
			},
			{
				name: 'file',
				param: 'binaryPropertyName',
				location: 'file',
				type: 'string',
				required: false,
			},
		],
	},
	validate_invoice: {
		method: 'POST',
		path: '/v1/validate',
		body: 'form',
		fields: [
			{
				name: 'explain',
				param: 'explain',
				location: 'query',
				type: 'boolean',
				required: false,
			},
			{
				name: 'lang',
				param: 'lang',
				location: 'query',
				type: 'string',
				required: false,
			},
			{
				name: 'file',
				param: 'binaryPropertyName',
				location: 'file',
				type: 'string',
				required: true,
			},
		],
	},
};

export class Invowerk implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'invowerk',
		name: 'invowerk',
		icon: {
			light: 'file:../../icons/invowerk.svg',
			dark: 'file:../../icons/invowerk.svg',
		},
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: 'Create XRechnung and EN 16931 e-invoices from your data, and read incoming XRechnung, ZUGFeRD and Factur-X invoices into fields',
		defaults: {
			name: 'invowerk',
		},
		usableAsTool: true,
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		credentials: [
			{
				name: 'invowerkApi',
				required: true,
			},
		],
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				options: [
					{
						name: 'Account',
						value: 'account',
					},
					{
						name: 'Invowerk',
						value: 'invowerk',
					},
				],
				default: 'invowerk',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: {
					show: {
						resource: ['account'],
					},
				},
				options: [
					{
						name: 'Get Me',
						value: 'get_me',
						description: 'Your plan, remaining requests, and remaining credits',
						action: 'Get me',
					},
				],
				default: 'get_me',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
					},
				},
				options: [
					{
						name: 'Convert Invoice',
						value: 'convert_invoice',
						description: 'Convert an e-invoice between UBL and CII',
						action: 'Convert invoice',
					},
					{
						name: 'Explain Codes',
						value: 'explain_codes',
						description: 'Explain an error code',
						action: 'Explain codes',
					},
					{
						name: 'Generate Invoice',
						value: 'generate_invoice',
						description: 'Create an e-invoice from JSON',
						action: 'Generate invoice',
					},
					{
						name: 'Parse Invoice',
						value: 'parse_invoice',
						description: 'Read an e-invoice into JSON',
						action: 'Parse invoice',
					},
					{
						name: 'Render Invoice',
						value: 'render_invoice',
						description: 'Render an e-invoice as HTML',
						action: 'Render invoice',
					},
					{
						name: 'Validate Invoice',
						value: 'validate_invoice',
						description: 'Check an e-invoice',
						action: 'Validate invoice',
					},
				],
				default: 'parse_invoice',
			},
			{
				displayName: 'Input Binary Field',
				name: 'binaryPropertyName',
				type: 'string',
				default: 'data',
				hint: 'The name of the input binary field containing the file to be uploaded',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['parse_invoice'],
					},
				},
				description: 'The invoice file (XML or PDF)',
			},
			{
				displayName: 'Target Syntax',
				name: 'targetSyntax',
				type: 'options',
				options: [
					{
						name: 'CII',
						value: 'cii',
					},
					{
						name: 'UBL',
						value: 'ubl',
					},
				],
				default: 'cii',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['convert_invoice'],
					},
				},
				description: 'The XML syntax to convert to: \'cii\' or \'ubl\'',
			},
			{
				displayName: 'Input Binary Field',
				name: 'binaryPropertyName',
				type: 'string',
				default: 'data',
				hint: 'The name of the input binary field containing the file to be uploaded',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['convert_invoice'],
					},
				},
				description: 'The invoice file (XML or PDF)',
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['convert_invoice'],
					},
				},
				options: [
					{
						displayName: 'Format',
						name: 'format',
						type: 'string',
						default: '',
						description: '\'JSON\' returns {xml, syntax, flavor, self_validation}; omitted returns raw application/xml',
					},
					{
						displayName: 'Target Flavor',
						name: 'targetFlavor',
						type: 'options',
						options: [
							{
								name: 'En16931',
								value: 'en16931',
							},
							{
								name: 'Xrechnung',
								value: 'xrechnung',
							},
						],
						default: 'en16931',
						description: 'Optional rule set of the result: \'en16931\' or \'xrechnung\'. Without it the flavor of the source is kept.',
					},
				],
			},
			{
				displayName: 'Invoice Number',
				name: 'invoiceNumber',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['generate_invoice'],
					},
				},
				description: 'Invoice number (BT-1)',
			},
			{
				displayName: 'Issue Date',
				name: 'issueDate',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['generate_invoice'],
					},
				},
				description: 'Issue date, \'YYYY-MM-DD\' (BT-2)',
			},
			{
				displayName: 'Seller',
				name: 'seller',
				type: 'json',
				default: '{}',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['generate_invoice'],
					},
				},
				description: 'The seller (BG-4)',
			},
			{
				displayName: 'Buyer',
				name: 'buyer',
				type: 'json',
				default: '{}',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['generate_invoice'],
					},
				},
				description: 'The buyer (BG-7)',
			},
			{
				displayName: 'Lines',
				name: 'lines',
				type: 'json',
				default: '[]',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['generate_invoice'],
					},
				},
				description: 'One or more invoice lines (BG-25)',
			},
			{
				displayName: 'Tax Breakdown',
				name: 'taxBreakdown',
				type: 'json',
				default: '[]',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['generate_invoice'],
					},
				},
				description: 'One or more VAT breakdowns, one per VAT category and rate (BG-23)',
			},
			{
				displayName: 'Totals',
				name: 'totals',
				type: 'json',
				default: '{}',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['generate_invoice'],
					},
				},
				description: 'The document totals (BG-22)',
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['generate_invoice'],
					},
				},
				options: [
					{
						displayName: 'Buyer Reference',
						name: 'buyerReference',
						type: 'string',
						default: '',
						description: 'Buyer reference, in Germany often the Leitweg-ID (BT-10). Required for flavor \'xrechnung\' (BR-DE-15), optional for plain EN 16931.',
					},
					{
						displayName: 'Currency',
						name: 'currency',
						type: 'string',
						default: 'EUR',
						description: 'Currency code, ISO 4217, e.g. \'EUR\' (BT-5)',
					},
					{
						displayName: 'Due Date',
						name: 'dueDate',
						type: 'string',
						default: '',
						description: 'Payment due date, \'YYYY-MM-DD\' (BT-9)',
					},
					{
						displayName: 'Flavor',
						name: 'flavor',
						type: 'options',
						options: [
							{
								name: 'En16931',
								value: 'en16931',
							},
							{
								name: 'Xrechnung',
								value: 'xrechnung',
							},
						],
						default: 'en16931',
						description: 'Rule set: \'en16931\' (plain EN 16931) or \'xrechnung\' (German rules)',
					},
					{
						displayName: 'Format',
						name: 'format',
						type: 'string',
						default: '',
						description: '\'JSON\' returns {xml, syntax, flavor, self_validation}; omitted returns raw application/xml',
					},
					{
						displayName: 'Invoice Type Code',
						name: 'invoiceTypeCode',
						type: 'string',
						default: '380',
						description: 'Invoice type code from UNTDID 1001; \'380\' is a commercial invoice (BT-3)',
					},
					{
						displayName: 'Payment IBAN',
						name: 'paymentIban',
						type: 'string',
						default: '',
						description: 'IBAN of the payee account for a bank transfer (BT-84)',
					},
					{
						displayName: 'Syntax',
						name: 'syntax',
						type: 'options',
						options: [
							{
								name: 'CII',
								value: 'cii',
							},
							{
								name: 'UBL',
								value: 'ubl',
							},
						],
						default: 'ubl',
						description: 'XML syntax of the invoice: \'ubl\' or \'cii\'',
					},
				],
			},
			{
				displayName: 'Code',
				name: 'code',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['explain_codes'],
					},
				},
				description: 'Comma-separated values. One or more codes; repeat the parameter: ?code=BR-DE-21&code=IW-IBAN.',
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['explain_codes'],
					},
				},
				options: [
					{
						displayName: 'Lang',
						name: 'lang',
						type: 'string',
						default: '',
						description: 'Language of the explanation, \'de\' or \'en\'. Without it, the Accept-Language header decides, otherwise German.',
					},
				],
			},
			{
				displayName: 'Input Binary Field',
				name: 'binaryPropertyName',
				type: 'string',
				default: 'data',
				hint: 'The name of the input binary field containing the file to be uploaded',
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['render_invoice'],
					},
				},
				description: 'The invoice XML as a multipart file part',
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['render_invoice'],
					},
				},
				options: [
					{
						displayName: 'Format',
						name: 'format',
						type: 'string',
						default: '',
						description: '\'JSON\' returns {html, lang, flavor, syntax}; omitted returns raw text/html',
					},
					{
						displayName: 'Lang',
						name: 'lang',
						type: 'string',
						default: '',
						description: 'Label language, \'de\' or \'en\'. Default: Accept-Language, then \'de\'.',
					},
				],
			},
			{
				displayName: 'Input Binary Field',
				name: 'binaryPropertyName',
				type: 'string',
				default: 'data',
				hint: 'The name of the input binary field containing the file to be uploaded',
				required: true,
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['validate_invoice'],
					},
				},
				description: 'The invoice file (XML or PDF)',
			},
			{
				displayName: 'Additional Fields',
				name: 'additionalFields',
				type: 'collection',
				placeholder: 'Add Field',
				default: {},
				displayOptions: {
					show: {
						resource: ['invowerk'],
						operation: ['validate_invoice'],
					},
				},
				options: [
					{
						displayName: 'Explain',
						name: 'explain',
						type: 'boolean',
						default: false,
						description: 'Whether to set explain',
					},
					{
						displayName: 'Lang',
						name: 'lang',
						type: 'string',
						default: 'de',
					},
				],
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			try {
				const op = OPERATIONS[this.getNodeParameter('operation', i) as string];
				let response = await send(this, op, i);
				if (op.job) {
					const submitted = (await decode(this, response, i)).json;
					response = await runJob(this, op.job, submitted, i);
				}
				out.push(await decode(this, response, i));
			} catch (error) {
				if (this.continueOnFail()) {
					out.push({ json: { error: (error as Error).message }, pairedItem: { item: i } });
					continue;
				}
				throw new NodeApiError(this.getNode(), error as JsonObject, { itemIndex: i });
			}
		}
		return [out];
	}
}
