"""invowerk: Explain codes. Generated by listing-sync (infra scripts/listing_sync/connectors/dify.py); edits are overwritten."""

from collections.abc import Generator
from typing import Any

from dify_plugin import Tool
from dify_plugin.entities.tool import ToolInvokeMessage

from tools._client import call

OPERATION = {
    "method": "GET",
    "path": "/v1/explain",
    "body": "",
    "fields": [
        {
            "name": "code",
            "location": "query",
            "type": "array"
        },
        {
            "name": "lang",
            "location": "query",
            "type": "string"
        }
    ]
}


class ExplainCodesTool(Tool):
    def _invoke(self, tool_parameters: dict[str, Any]) -> Generator[ToolInvokeMessage]:
        yield from call(self, OPERATION, tool_parameters)
