"""invowerk: Generate invoice. Generated by listing-sync (infra scripts/listing_sync/connectors/dify.py); edits are overwritten."""

from collections.abc import Generator
from typing import Any

from dify_plugin import Tool
from dify_plugin.entities.tool import ToolInvokeMessage

from tools._client import call

OPERATION = {
    "method": "POST",
    "path": "/v1/generate",
    "body": "json",
    "fields": [
        {
            "name": "format",
            "location": "query",
            "type": "string"
        },
        {
            "name": "syntax",
            "location": "json",
            "type": "string"
        },
        {
            "name": "flavor",
            "location": "json",
            "type": "string"
        },
        {
            "name": "invoice_number",
            "location": "json",
            "type": "string"
        },
        {
            "name": "issue_date",
            "location": "json",
            "type": "string"
        },
        {
            "name": "currency",
            "location": "json",
            "type": "string"
        },
        {
            "name": "invoice_type_code",
            "location": "json",
            "type": "string"
        },
        {
            "name": "buyer_reference",
            "location": "json",
            "type": "string"
        },
        {
            "name": "due_date",
            "location": "json",
            "type": "string"
        },
        {
            "name": "payment_iban",
            "location": "json",
            "type": "string"
        },
        {
            "name": "seller",
            "location": "json",
            "type": "object"
        },
        {
            "name": "buyer",
            "location": "json",
            "type": "object"
        },
        {
            "name": "lines",
            "location": "json",
            "type": "array"
        },
        {
            "name": "tax_breakdown",
            "location": "json",
            "type": "array"
        },
        {
            "name": "totals",
            "location": "json",
            "type": "object"
        }
    ]
}


class GenerateInvoiceTool(Tool):
    def _invoke(self, tool_parameters: dict[str, Any]) -> Generator[ToolInvokeMessage]:
        yield from call(self, OPERATION, tool_parameters)
